cart/urls.py
from django.urls import path
from .views import *
from ecommece_moon.settings import *

urlpatterns = [
    path('', cart, name='cart'),
    path('add_product/<int:product_id>/', add_cart, name='add_cart'),
    path('sub_product/<int:product_id>/', sub_cart, name='sub_cart'),
    path('delete/<int:product_id>/', remove_cart, name='delete_cart_item'),

]

ecommece_moon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from ecommece_moon.settings import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home, name = "home"),
    path("store/", include('store.urls')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
  
] + static(MEDIA_URL, document_root = MEDIA_ROOT)

store/urls.py
from .views import *
from django.urls import path




urlpatterns = [
    path('', store, name='store'),
    path('<slug:category_slug>', store, name='product_slug'),
    path('<slug:category_slug>/<slug:product_slug>', product_detail, name='product_detail'),
]

wishlist/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.asosiy, name='wishlist'),
    path('add-to-wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import Product

class Cart(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    session_id = models.CharField(max_length=3000, 
                                    blank=True, 
                                    null=True, 
                                    default=" ")

    def is_empty(self):
        return self.cartitem_set.count() == 0

    def clear_cart(self):
        self.cartitem_set.all().delete()

    def get_item_count(self):
        return self.cartitem_set.count()

    def remove_item(self, cart_item_id):
        try:
            cart_item = self.cartitem_set.get(id=cart_item_id)
            cart_item.delete()
        except CartItem.DoesNotExist:
            pass

    def update_item_quantity(self, cart_item_id, quantity):
        try:
            cart_item = self.cartitem_set.get(id=cart_item_id)
            if quantity > 0:
                cart_item.quantity = quantity
                cart_item.save()
            else:
                cart_item.delete()
        except CartItem.DoesNotExist:
            pass
            
        
        
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def toggle_active(self):
        self.is_active = not self.is_active
        self.save()

    def increment_quantity(self):
        self.quantity += 1
        self.save()

    def decrement_quantity(self):
        if self.quantity > 1:
            self.quantity -= 1
            self.save()

    def get_subtotal_price(self):
        return self.product.price * self.quantity

    

    def is_in_stock(self):
        return self.product.stock >= self.quantity
    
    
    
    

store/models.py
from django.db import models
from category.models import Category
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Maxsulot nomi', unique=True)
    slug = models.SlugField(max_length=50, unique=True, help_text='Slug for the category' )
    description = models.TextField(verbose_name='Description nomi')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Narxi')
    image = models.ImageField(upload_to='prod_image/product_image')
    chegirma = models.IntegerField(null=True, blank=True,default=0,
                                    validators=[
                                        MinValueValidator(0,
                                                          message='Satish mikdori 0 yoki undan katta bo\'lishi kerak.'),
                                         MaxValueValidator(100,
                                                             message='Sotish mikdori 100 yoki undan kam bo\'lishi kerak.')],)
    stock = models.IntegerField(verbose_name='Sotish Mikdori', help_text='Maxsulot soni')
    true_price = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, default=0, verbose_name='Haqiqiy narx')
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category nomi')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
        
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name = 'product'
        verbose_name_plural = 'products'
        
        
    def save(self, *args, **kwargs):

        if self.chegirma is not None and self.price is not None:
            total = self.price - (self.price * self.chegirma / 100)
            self.true_price = total
        super().save(*args, **kwargs)
        
    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])


    def get_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return '/path/to/default/image.jpg'

    def get_discounted_price(self):
        if self.chegirma is not None and self.price is not None:
            discounted_price = self.price - (self.price * self.chegirma / 100)
            return discounted_price
        return None


    def get_formatted_discount(self):
        if self.chegirma is not None:
            return f"{self.chegirma}%"

        return None


    def get_formatted_created_date(self):
        return self.created_date.strftime('%Y-%m-%d')

    def get_formatted_modified_date(self):
        return self.modified_date.strftime('%Y-%m-%d')
    
    

ulcham_uchun/models.py
from django.db import models
from store.models import Product









    
ulcham_turlarini_tanlash = (
    ('color ', 'color'),
    ('size', 'size'),

)    


class Ulchamlar(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ulcham_turlari = models.CharField(max_length=20, choices=ulcham_turlarini_tanlash)
    ulcham_qiymat = models.CharField(max_length=40)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.name} - {self.ulcham_turlari}: {self.ulcham_qiymat}"

    def __unicode__(self):
        return self.product

wishlist/models.py
from django.db import models
from store.models import Product
from django.utils import timezone

class Wishlist(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    session_id = models.CharField(max_length=3000, blank=True, null=True, default="")

    def __str__(self):
        return f"Wishlist {self.session_id}"

    def add_item(self, product):
        item, created = Wishlist_Item.objects.get_or_create(wishlist=self, product=product)
        self.modified_date = timezone.now()
        self.save()
        return item

    def remove_item(self, product):
        item = Wishlist_Item.objects.filter(wishlist=self, product=product).first()
        if item:
            item.delete()
            self.modified_date = timezone.now()
            self.save()

    def clear(self):
        Wishlist_Item.objects.filter(wishlist=self).delete()
        self.modified_date = timezone.now()
        self.save()

    @property
    def total_items(self):
        return Wishlist_Item.objects.filter(wishlist=self).count()

class Wishlist_Item(models.Model):
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.name} in {self.wishlist.session_id}"

    def save(self, *args, **kwargs):
        self.wishlist.modified_date = timezone.now()
        self.wishlist.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.wishlist.modified_date = timezone.now()
        self.wishlist.save()
        super().delete(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']
        unique_together = ('wishlist', 'product')
        verbose_name = 'Wishlist Item'
        verbose_name_plural = 'Wishlist Items'

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse




def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart



def cart(request):
    try:
        cart = Cart.objects.get(session_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        total = 0
        for i in cart_items:
            total += i.quantity * i.product.true_price
        
        soliq = (total * 2) / 100
        true_total = total - soliq
    except Cart.DoesNotExist:
        cart_items = []
        total = 0
        soliq = 0
        true_total = 0

    context = {
        'cart_items': cart_items,
        'total': total,
        'soliq': soliq, 
        'true_total': true_total
    }
    
    return render(request, 'cart.html', context)


def add_cart(request, product_id):
    color = request.GET["color"]
    size = request.GET["size"]
    return HttpResponse(color+" "+size)
    exit()
    
    product = get_object_or_404(Product.objects.select_related('category'), id=product_id)
    
    try:
        cart = Cart.objects.get(session_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(session_id=_cart_id(request))
        cart.save()
    
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, cart=cart, quantity=1)
        cart_item.save()
        
    return redirect('cart')


def sub_cart(request, product_id):
    product = get_object_or_404(Product.objects.select_related('category'), id=int(product_id))
    cart = Cart.objects.get(session_id=_cart_id(request))
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart')



def remove_cart(request, product_id):
    product = get_object_or_404(Product.objects.select_related('category'), id=int(product_id))
    cart = Cart.objects.get(session_id=_cart_id(request))
    cart_item = CartItem.objects.get(product=product, cart=cart)

    cart_item.delete()
    return redirect('cart')




# def delete(request, cart_item_id):
#     
#      cart = Cart.objects.get(session_id=_cart_id(request))
#         cart.remove_item(cart_item_id)
#     except Cart.DoesNotExist:
#         pass
#     return redirect('cart')

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from category.models import Category
from cart.models import CartItem
from cart.views import _cart_id
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug is not None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True).order_by('-created_date')
        # p = Paginator(products, 1)
        # page_number = request.GET.get('page')
        # page_obj = p.get_page(page_number)  

    else:
        products = Product.objects.filter(is_available=True)
      #  p = Paginator(products, 1)
     #   page_number = request.GET.get('page')
      # # page_obj = p.get_page(page_number)  

    
    
    category = Category.objects.all()
    context = {
       # 'page_obj':page_obj,
        'products': products,
        'product_count': products.count(),
        'categories': category,
    }
    return render(request, 'store.html', context)



def product_detail(request, category_slug, product_slug):
    try:
        product = Product.objects.get(slug=product_slug, category__slug=category_slug)
    except Exception as e:
        raise e
    
    
    context = {
        'product': product,
    }
    return render(request, "product_detail.html", context)

    

wishlist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product
from .models import Wishlist, Wishlist_Item
from django.http import JsonResponse
from cart.models import Cart, CartItem

def asosiy(request):
    wishlist_id = _wishlist_id(request)
    wishlist, created = Wishlist.objects.get_or_create(session_id=wishlist_id)
    wishlist_items = Wishlist_Item.objects.filter(wishlist=wishlist)
    context = {
        'wishlist_items': wishlist_items,
    }
    return render(request, 'wishlist.html', context)

def add_to_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist_id = _wishlist_id(request)

    try:
        wishlist = Wishlist.objects.get(session_id=wishlist_id)
    except Wishlist.DoesNotExist:
        wishlist = Wishlist.objects.create(session_id=wishlist_id)
        wishlist.save()

    try:
        wishlist_item = Wishlist_Item.objects.get(product=product, wishlist=wishlist)
    except Wishlist_Item.DoesNotExist:
        wishlist_item = Wishlist_Item.objects.create(product=product, wishlist=wishlist)
        wishlist_item.save()
    return redirect('wishlist')

def _wishlist_id(request):
    try:
        wishlist = request.session.session_key
        if not wishlist:
            wishlist = request.session.create()
        return wishlist
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

def remove_from_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist_id = _wishlist_id(request)
    wishlist = get_object_or_404(Wishlist, session_id=wishlist_id)
    wishlist_item = get_object_or_404(Wishlist_Item, wishlist=wishlist, product=product)
    wishlist_item.delete()
    return redirect('/')

def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)

    try:
        cart = Cart.objects.get(session_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(session_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, cart=cart, quantity=1)
        cart_item.save()
    
    return redirect('cart')

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>UPTUZ shop | One of the Biggest Online Shopping Platform</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{%  static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'css/responsive.css'%}" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

});
// jquery end
</script>

</head>
<body>


{% include 'header.html' %}

{% block content %}


{% endblock %}

{% include 'footer.html' %}

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}



{% block content%}


    
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    


{% if not cart_items %}
<div class="alert alert-primary" role="alert">
    cart mavjun emas
</div>
<a href="{% url 'store' %}" type="button" class="btn btn-primary">shop</a>
{% else %}
    

    

    <div class="row">
        <aside class="col-lg-9">
        <div class="card">
        <table class="table table-borderless table-shopping-cart">
        <thead class="text-muted">
        <tr class="small text-uppercase">
        <th scope="col">Product</th>
        <th scope="col" width="120">Quantity</th>
        <th scope="col" width="120">Price</th>
        <th scope="col" class="text-right" width="200"> </th>
        </tr>
        </thead>
        <tbody>
        
        {% for i in cart_items %}
            
            <tr>
                <td>
                    <figure class="itemside align-items-center">
                        <div class="aside"><img src="{{i.product.image.url}}" class="img-sm"></div>
                        <figcaption class="info">
                            <a href="{{i.product.get_url}}" class="title text-dark">{{i.product.name}}</a>
                            <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                        </figcaption>
                    </figure>
                </td>
                <td> 
                    <!-- col.// -->
                    <div class="col"> 
                        <div class="input-group input-spinner">
                            <div class="input-group-prepend">
                                <a href="{% url 'sub_cart' i.product.id %}" class="btn btn-light" type="button" id="button-plus">
                                    <i class="fa fa-minus"></i>
                                </a>
                            </div>
                            <input type="text" class="form-control" value="{{ i.quantity }}">
                            <div class="input-group-append">
                                <a href="{% url 'add_cart' i.product.id %}" class="btn btn-light" type="button" id="button-minus">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div> <!-- input-group.// -->
                    </div>  
                
                </td>
                <td> 
                    <div class="price-wrap"> 
                        <var class="price">${{i.get_subtotal_price}}</var> 
                        <small class="text-muted"> ${{i.product.price}} each </small> 

                        <small class="text-muted"> ${{i.product.true_price}} each </small> 
                    </div> <!-- price-wrap .// -->
                </td>
                <td class="text-right"> 
                <a href="{% url 'delete_cart_item' i.product.id  %}" class="btn btn-danger"> Remove</a>
                </td>
            </tr>

            {% endfor %}
        </tbody>
        </table>
        </div> <!-- card.// -->
        
            </aside> <!-- col.// -->
            <aside class="col-lg-3">
        
                <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                    <dt>Total price:</dt>
                    <dd class="text-right">${{total}}</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Tax:</dt>
                    <dd class="text-right"> ${{soliq}}</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Total:</dt>
                    <dd class="text-right text-dark b"><strong>${{true_total}}</strong></dd>
                    </dl>
                    <hr>
                    <p class="text-center mb-3">
                        <img src="./images/misc/payments.png" height="26">
                    </p>
                    <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                    <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
                </div> <!-- card-body.// -->
                </div> <!-- card.// -->
        
        </aside> <!-- col.// -->
        
    
    </div> <!-- row.// -->
    
{% endif %}


<!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
</section>


{% endblock %}

templates/footer.html
{% load static %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> UPTUZ Samur </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">qaz1221samur@gmail.com</span>
				<span  class="px-2">+99890-45-11-173</span>
				<span  class="px-2">Urgut</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/header.html
{% load static %}

<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link">   English </a>

		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link"> USD </a>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="./" class="brand-wrap">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-bars"></i> All category
			</button>
			<div class="dropdown-menu">
				<a class="dropdown-item" href="{% url 'store' %}">All products</a>

				{% for i in categories %}
					<a class="dropdown-item" href="{{i.get_url}}">{{i.name}}</a>
				{% endfor %}
			
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
	<a href="{% url 'store' %}" class="btn btn-outline-primary">Store</a>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="#" class="search">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search">

			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
				<div class="d-flex justify-content-end mb-3 mb-lg-0">
					<div class="widget-header">
						<small class="title text-muted">Welcome guest!</small>
						<div>
							<a href="./signin.html">Sign in</a> <span class="dark-transp"> | </span>
							<a href="./register.html"> Register</a>
						</div>
					</div>
					<a href="{% url 'cart' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{cart_count}}</span>
					</a>
					<a href="{% url 'wishlist' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border">
						  <i class="fa fa-heart"></i>
						</div>
						<span class="badge badge-pill badge-danger notify">{{ wishlist_count }}</span>
					</a>
					  
					  
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->




</header> <!-- section-header.// -->

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}



{% block content%}



<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap">
	   <a href="#"><img src="{{product.image.url}}"></a>
	</div> <!-- img-big-wrap.// -->


	<form action="{% url 'add_cart' product.id %}" method = "GET">

		</article> <!-- gallery-wrap .end// -->
				</aside>
				<main class="col-md-6 border-left">
		<article class="content-body">

		<h2 class="title">{{ product.name }}</h2>

		<div class="mb-3">
			{% if product.chegirma > 0 %}
				<var class="price h4"><del>{{ product.price|floatformat:2 }}</del></var>
			<br>
				
			<var class="price h4">{{ product.true_price|floatformat:2 }}</var>
			{% else %}
		<br>
				<var class="price h4">{{ product.price|floatformat:2 }}</var>
			{% endif %}
		</div>


		<p>{{ product.description }}</p>

		<hr>
			<div class="row">
				<div class="item-option-select">
					<h6>Choose Color</h6>
					<select name="color" class="form-control" required>
						<option value="" disabled selected>Choose Color</option>
						{% for i in product.ulchamlar_set.all %}
						<option value="{{i.ulcham_qiymat}}">{{i.ulcham_qiymat}}</option>
							
						{% endfor %}
							

					</select>
				</div>
			</div> <!-- row.// -->
			<div class="row">
				<div class="item-option-select">
					<h6>Select Size</h6>
					<select name="size" class="form-control">
						<option value="small">Small</option>
						<option value="medium">Medium</option>
						<option value="large">Large</option>
						<option value="extra large">Extra Large</option>

					</select>
				</div>
			</div> <!-- row.// -->
			<hr>
			{% if product.stock < 0 %}
				<h5 class="btn  btn-danger"> Out of stock </h5>

			{% else %}
				
				{% if is_cart %}
					<a href="{% url 'add_cart' product.id %}" class="btn  btn-primary"> <span class="text">Cart mavjud</span> <i class="fas fa-check"></i> </a>
					
				{% else %}
					<button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i> </a>
					
				{% endif %}
			
			{% endif %}


		</article> <!-- product-info-aside .// -->
	</form>
		{% if is_cart %}
			<a href="{% url 'add_to_wishlist' product.id %}" class="btn btn-success"> <span class="text">Add to wishlist</span> <i class="fas fa-shopping-cart"></i> </a>
			
		{% else %}
				<a href="{% url 'add_to_wishlist' product.id %}" class="btn btn-success"> <span class="text">Add to wishlist</span> <i class="fas fa-shopping-cart"></i> </a>
			
		{% endif %}
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>

	</header>

	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">24.04.2020 </span>
				<h6 class="mb-1">Mike John </h6>

			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<p>
				Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip
			</p>
		</div>
	</article>



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}